spring:
  config:
    import: aws-secretsmanager:prod/device-res/postgres?prefix=db.

  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/postgres
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
